@startuml H4x2_userflow
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/aws-orange-light/puml-theme-aws-orange-light.puml


title H4x2 User Flow

partition "**precondition**" {
    :password : account password
    PRISM : Augmented password
    PRISMi : Partial of a PRISM.  Each node holds a PRISMi
    ORK t - Tide hosted ORK nodes
    ORK n - User hosted ORK nodes
    Secret - Secret to be encrypted
    ]
}
-[#white,dashed]->;

start
->request sign-up Page from Vendor;
    repeat :Enter username;
    :Enter password;
    :Repeat password;
    :Enter Secret; 
    :Choose ORK Nodes //<color blue> 1 Tide Hosted node as a prerequisite.  \n <color blue> 4 other nodes based on user preference//; 
    :Send to Simulator;
    backward :Invalid username;
    repeat while (username exist) is (yes) not (no)
    note left: username exist
    repeat
    partition "**ORK Nodes**" {
        :Store in ORK Nodes;
        note right: PrismAuth, userID, Prism, CVK    
        :Sign Entry to the Simulator;
    }
    repeat while (inValid) 
    
    partition "**Simulator**" {
        :write entry;
        note right: data is signed by the ORKs
        :confirm entry;
    }
stop 

@enduml